import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
	// Political markets being monitored
	markets: defineTable({
		polymarketId: v.string(),
		slug: v.string(),
		question: v.string(),
		category: v.string(),
		endDate: v.optional(v.number()),
		isActive: v.boolean(),
		totalVolume: v.number(),
		outcomes: v.array(
			v.object({
				name: v.string(),
				tokenId: v.string(),
				price: v.number(),
			}),
		),
		lastSyncedAt: v.number(),
	})
		.index("by_polymarket_id", ["polymarketId"])
		.index("by_category", ["category"])
		.index("by_active", ["isActive"]),

	// Trader accounts observed
	accounts: defineTable({
		address: v.string(),
		displayName: v.optional(v.string()),
		previousNames: v.array(v.string()),
		firstSeenAt: v.number(),
		createdAt: v.optional(v.number()),
		totalTrades: v.number(),
		totalVolume: v.number(),
		winCount: v.number(),
		lossCount: v.number(),
		winRate: v.number(),
		riskScore: v.number(),
		flags: v.array(v.string()),
		lastActivityAt: v.number(),
		isFlagged: v.boolean(),
	})
		.index("by_address", ["address"])
		.index("by_risk_score", ["riskScore"])
		.index("by_flagged", ["isFlagged"]),

	// Detection alerts generated by agent
	alerts: defineTable({
		accountId: v.id("accounts"),
		marketId: v.optional(v.id("markets")),
		severity: v.union(
			v.literal("low"),
			v.literal("medium"),
			v.literal("high"),
			v.literal("critical"),
		),
		signalType: v.union(
			v.literal("new_account_large_bet"),
			v.literal("timing_correlation"),
			v.literal("statistical_improbability"),
			v.literal("account_obfuscation"),
			v.literal("disproportionate_bet"),
			v.literal("pattern_match"),
		),
		title: v.string(),
		description: v.string(),
		evidence: v.object({
			metrics: v.any(),
			reasoning: v.string(),
		}),
		status: v.union(
			v.literal("new"),
			v.literal("investigating"),
			v.literal("confirmed"),
			v.literal("dismissed"),
		),
		createdAt: v.number(),
		updatedAt: v.number(),
		agentRunId: v.optional(v.id("agentRuns")),
	})
		.index("by_account", ["accountId"])
		.index("by_severity", ["severity"])
		.index("by_status", ["status"])
		.index("by_created", ["createdAt"]),

	// Agent execution logs
	agentRuns: defineTable({
		startedAt: v.number(),
		completedAt: v.optional(v.number()),
		status: v.union(
			v.literal("running"),
			v.literal("completed"),
			v.literal("failed"),
		),
		triggerType: v.union(
			v.literal("scheduled"),
			v.literal("manual"),
			v.literal("realtime_trigger"),
		),
		marketIds: v.array(v.id("markets")),
		accountsAnalyzed: v.number(),
		alertsGenerated: v.number(),
		toolCalls: v.array(
			v.object({
				tool: v.string(),
				input: v.any(),
				output: v.any(),
				timestamp: v.number(),
			}),
		),
		tokensUsed: v.object({
			input: v.number(),
			output: v.number(),
		}),
		error: v.optional(v.string()),
	})
		.index("by_started", ["startedAt"])
		.index("by_status", ["status"]),

	// Real-time activity feed for UI
	activityFeed: defineTable({
		type: v.union(
			v.literal("trade_detected"),
			v.literal("alert_created"),
			v.literal("agent_started"),
			v.literal("agent_completed"),
			v.literal("market_synced"),
		),
		payload: v.any(),
		timestamp: v.number(),
	}).index("by_timestamp", ["timestamp"]),
});
