/* eslint-disable */
/**
 * Generated stub for Convex API.
 * This file is auto-generated by Convex - DO NOT EDIT manually.
 */

import type {
	ApiFromModules,
	FilterApi,
	FunctionReference,
} from "convex/server";

// Import all function modules
import * as accounts from "../accounts";
import * as activityFeed from "../activityFeed";
import * as alerts from "../alerts";
import * as agentRuns from "../agentRuns";
import * as markets from "../markets";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
	accounts: typeof accounts;
	activityFeed: typeof activityFeed;
	alerts: typeof alerts;
	agentRuns: typeof agentRuns;
	markets: typeof markets;
}>;

export declare const api: FilterApi<
	typeof fullApi,
	FunctionReference<"public">
>;

export declare const internal: FilterApi<
	typeof fullApi,
	FunctionReference<"internal">
>;
