/* eslint-disable */
/**
 * Generated stub for Convex data model types.
 * This file is auto-generated by Convex - DO NOT EDIT manually.
 */

import type { GenericDataModel, GenericDocument, GenericId } from "convex/server";

// Table document types
export interface Market {
	_id: GenericId<"markets">;
	_creationTime: number;
	polymarketId: string;
	slug: string;
	question: string;
	category: string;
	endDate?: number;
	isActive: boolean;
	totalVolume: number;
	outcomes: Array<{
		name: string;
		tokenId: string;
		price: number;
	}>;
	lastSyncedAt: number;
}

export interface Account {
	_id: GenericId<"accounts">;
	_creationTime: number;
	address: string;
	displayName?: string;
	previousNames: string[];
	firstSeenAt: number;
	createdAt?: number;
	totalTrades: number;
	totalVolume: number;
	winCount: number;
	lossCount: number;
	winRate: number;
	riskScore: number;
	flags: string[];
	lastActivityAt: number;
	isFlagged: boolean;
}

export interface Alert {
	_id: GenericId<"alerts">;
	_creationTime: number;
	accountId: GenericId<"accounts">;
	marketId?: GenericId<"markets">;
	severity: "low" | "medium" | "high" | "critical";
	signalType:
		| "new_account_large_bet"
		| "timing_correlation"
		| "statistical_improbability"
		| "account_obfuscation"
		| "disproportionate_bet"
		| "pattern_match";
	title: string;
	description: string;
	evidence: {
		metrics: unknown;
		reasoning: string;
	};
	status: "new" | "investigating" | "confirmed" | "dismissed";
	createdAt: number;
	updatedAt: number;
	agentRunId?: GenericId<"agentRuns">;
}

export interface AgentRun {
	_id: GenericId<"agentRuns">;
	_creationTime: number;
	startedAt: number;
	completedAt?: number;
	status: "running" | "completed" | "failed";
	triggerType: "scheduled" | "manual" | "realtime_trigger";
	marketIds: GenericId<"markets">[];
	accountsAnalyzed: number;
	alertsGenerated: number;
	toolCalls: Array<{
		tool: string;
		input: unknown;
		output: unknown;
		timestamp: number;
	}>;
	tokensUsed: {
		input: number;
		output: number;
	};
	error?: string;
}

export interface ActivityFeedItem {
	_id: GenericId<"activityFeed">;
	_creationTime: number;
	type:
		| "trade_detected"
		| "alert_created"
		| "agent_started"
		| "agent_completed"
		| "market_synced";
	payload: unknown;
	timestamp: number;
}

// Table name to document type mapping
export interface Tables {
	markets: Market;
	accounts: Account;
	alerts: Alert;
	agentRuns: AgentRun;
	activityFeed: ActivityFeedItem;
}

// DataModel type
export type DataModel = GenericDataModel & {
	tables: Tables;
};

// Id type helper
export type Id<TableName extends keyof Tables> = GenericId<TableName>;
