/* eslint-disable */
/**
 * Generated stub for Convex server functions.
 * This file is auto-generated by Convex - DO NOT EDIT manually.
 * For local development without a Convex backend, this stub provides types.
 */

import {
	actionGeneric,
	httpActionGeneric,
	queryGeneric,
	mutationGeneric,
	internalActionGeneric,
	internalMutationGeneric,
	internalQueryGeneric,
} from "convex/server";
import type { DataModel } from "./dataModel";

/**
 * Define a query in this Convex app's public API.
 */
export const query = queryGeneric as typeof queryGeneric<DataModel>;

/**
 * Define a mutation in this Convex app's public API.
 */
export const mutation = mutationGeneric as typeof mutationGeneric<DataModel>;

/**
 * Define an action in this Convex app's public API.
 */
export const action = actionGeneric as typeof actionGeneric<DataModel>;

/**
 * Define an HTTP action.
 */
export const httpAction = httpActionGeneric;

/**
 * Define an internal query.
 */
export const internalQuery =
	internalQueryGeneric as typeof internalQueryGeneric<DataModel>;

/**
 * Define an internal mutation.
 */
export const internalMutation =
	internalMutationGeneric as typeof internalMutationGeneric<DataModel>;

/**
 * Define an internal action.
 */
export const internalAction =
	internalActionGeneric as typeof internalActionGeneric<DataModel>;
